const fs = require('fs');
const B = 'C:/Users/mastr/claude co/legal-docs/blog/';
fs.mkdirSync(B, {recursive:true});

var NAV = '<header class="site-header"><div class="header-inner"><a href="/" class="site-logo">FreeDoc<span>Templates</span></a><nav class="main-nav" aria-label="Main"><div class="nav-group"><button class="nav-trigger" aria-haspopup="true" aria-expanded="false">Templates <svg class="nav-chevron" width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" stroke-width="2"><path d="M2 4l4 4 4-4"/></svg></button><div class="nav-dropdown"><a href="/lease-agreement-template" class="nav-item">Lease Agreement</a><a href="/eviction-notice-template" class="nav-item">Eviction Notice</a><a href="/bill-of-sale-template" class="nav-item">Bill of Sale</a><a href="/quitclaim-deed-template" class="nav-item">Quitclaim Deed</a><a href="/power-of-attorney-template" class="nav-item">Power of Attorney</a></div></div></nav><div class="header-actions"><a href="/tools" class="btn-all-tools">All Templates</a><button id="btn-search" class="btn-search" aria-label="Search"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><path d="M21 21l-4.35-4.35"/></svg></button></div></div></header><div class="cmd-overlay" id="cmd-overlay"><div class="cmd-modal"><div class="cmd-header"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><path d="M21 21l-4.35-4.35"/></svg><input class="cmd-input" id="cmd-input" placeholder="Search templates\u2026" autocomplete="off"></div><div class="cmd-body" id="cmd-body"></div></div></div>';
var FTR = '<footer class="site-footer"><div class="container"><div class="footer-grid"><div><a href="/" class="footer-logo">FreeDocTemplates</a><p class="footer-tagline">Free legal document templates. No sign-up, no watermarks.</p></div><div><div class="footer-col-title">Templates</div><nav class="footer-nav"><a href="/lease-agreement-template">Lease Agreement</a><a href="/eviction-notice-template">Eviction Notice</a><a href="/quitclaim-deed-template">Quitclaim Deed</a><a href="/power-of-attorney-template">Power of Attorney</a></nav></div></div><div class="footer-bottom"><p>\u00a9 2026 FreeDocTemplates.xyz</p></div></div></footer>';

function wrap(title,desc,canon,body){return '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+'</title><meta name="description" content="'+desc+'"><link rel="canonical" href="https://www.freedoctemplates.xyz/blog/'+canon+'"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap"><link rel="stylesheet" href="/shared/styles.css?v=1"></head><body>'+NAV+'<main class="page-wrap">'+body+'</main>'+FTR+'<script src="/shared/scripts.js?v=1" defer><\/script></body></html>';}
function sec(h2,paras){return '<h2 style="font-size:20px;font-weight:700;color:var(--ink-1);margin:32px 0 12px">'+h2+'</h2>'+paras.map(function(p){return '<p style="color:var(--ink-2);line-height:1.75;margin-bottom:14px">'+p+'</p>';}).join('');}
function faqs(list){return '<section class="faq-section" style="margin:40px -24px 0;padding:48px 24px"><div class="faq-header"><p class="section-eyebrow">FAQ</p></div><div class="faq-list">'+list.map(function(f){return '<details class="faq-item"><summary class="faq-q">'+f.q+'</summary><div class="faq-a">'+f.a+'</div></details>';}).join('')+'</div></section>';}
function cta(text,href){return '<div style="background:var(--surface-2);border:1px solid var(--border);border-radius:12px;padding:24px;text-align:center;margin:32px 0"><p style="font-weight:600;color:var(--ink-1);margin-bottom:10px">'+text+'</p><a href="'+href+'" style="display:inline-block;padding:11px 26px;background:var(--accent);color:#fff;border-radius:8px;font-weight:600;text-decoration:none">Get Free Template &#8594;</a></div>';}

function art(slug,title,desc,intro,secs,faqList,ctaTxt,ctaHref){
  var body='<div class="container"><nav class="breadcrumb"><a href="/">Home</a><span>&#8250;</span><a href="/blog">Blog</a><span>&#8250;</span><span aria-current="page">'+title+'</span></nav><h1 class="page-title" data-enter>'+title+'</h1><p class="page-sub" data-enter data-delay="1">'+intro+'</p></div><div class="container" style="max-width:760px;margin-top:32px">'+secs.map(function(s){return sec(s.h,s.p);}).join('')+cta(ctaTxt,ctaHref)+faqs(faqList)+'</div>';
  return wrap(title+' | FreeDocTemplates',desc,slug,body);
}

var posts=[

{slug:'just-cause-eviction',title:'What Is Just Cause Eviction? Tenant Protections Explained',
desc:'Just cause eviction laws require landlords to have a legal reason to evict or end a tenancy. Learn which cities and states have them.',
intro:'In most of the US, landlords can end a month-to-month tenancy for any reason — or no reason — with 30 days\' notice. Just cause eviction laws change that entirely.',
secs:[
{h:'What "Just Cause" Means',p:['A just cause eviction ordinance prohibits landlords from evicting tenants without a legally recognized reason. The permitted reasons — called "just causes" — typically fall into two categories: <strong>at-fault causes</strong> (non-payment of rent, lease violations, criminal activity, subletting without permission) and <strong>no-fault causes</strong> (owner move-in, substantial renovation requiring vacancy, property demolition, Ellis Act withdrawal).',
'Without a just cause ordinance, landlords can issue a "no-fault, no-cause" termination — ending the tenancy without stating any reason. With just cause protection, that is illegal.']},
{h:'Where Just Cause Laws Apply',p:['Statewide: <strong>California</strong> (AB 1482, applies to most buildings over 15 years old), <strong>Oregon</strong> (SB 608), <strong>Washington</strong> (HB 1236). These are the only states with statewide just cause laws.',
'Major cities with local just cause ordinances: New York City (Good Cause Eviction Law), San Francisco, Los Angeles, Seattle, Portland, Oakland, Berkeley, San Jose, Minneapolis, Chicago (limited), Washington DC, Newark NJ, and dozens of others. If you live in a major metro, check your city\'s tenant rights office.']},
{h:'No-Fault Just Cause: Owner Move-In and Ellis Act',p:['Most just cause laws allow a no-fault eviction if the owner genuinely intends to move in (owner move-in, or OMI). Requirements are strict: the owner must actually move in within 90 days, stay for a minimum period (12 months in SF), and pay the tenant substantial relocation assistance (often 1–3 months\' rent).',
'The Ellis Act (California) allows landlords to evict all tenants from a building permanently if they are "going out of the rental business." San Francisco Ellis Act evictions require 120 days\' notice (1 year for elderly/disabled tenants) and relocation payments.']},
{h:'Proving Just Cause in Court',p:['Landlords in just cause jurisdictions must state the reason for termination in the notice itself — a blank "notice to vacate" is invalid. If a tenant fights the eviction, the landlord must prove the stated cause. Filing an eviction without valid just cause can expose the landlord to hefty penalties: wrongful eviction damages, attorney\'s fees, and sometimes three times actual damages.',
'For tenants: if you receive a no-fault notice in a just cause jurisdiction, research whether your building and tenancy are covered before moving out. Just cause exemptions are common (new construction under 15 years, single-family homes in some states, owner-occupied buildings with 2–4 units).']}
],
faqList:[
{q:'Does just cause eviction apply to month-to-month tenancies?',a:'Yes — that is the whole point. In most states, landlords can end month-to-month tenancies at will with 30 days\' notice. Just cause laws eliminate this ability, requiring a stated and legally recognized reason for all terminations, including month-to-month.'},
{q:'What happens if a landlord evicts a tenant without just cause in a covered city?',a:'The tenant can sue for wrongful eviction. Remedies vary by jurisdiction: San Francisco awards the greater of actual damages or three times the monthly rent, plus attorney\'s fees. New York City\'s Good Cause Eviction Law allows tenants to raise just cause as a defense in eviction court, which can result in dismissal.'},
{q:'Are all tenants covered by just cause laws?',a:'No. Most just cause laws have significant exemptions: newer construction (buildings under 10–15 years old), single-family homes (where the landlord has disclosed the exemption), condos being sold to owner-occupants, vacation rentals, and owner-occupied buildings with 2–4 units. Always verify whether your specific unit is covered.'},
{q:'Can a tenant waive just cause protections?',a:'No. Tenant protections created by law cannot be waived by lease agreement. A lease clause that says "tenant waives just cause protections" is void and unenforceable. Landlords cannot contract around local tenant protection ordinances.'}
],
ctaTxt:'Create a state-compliant eviction notice — free',ctaHref:'/eviction-notice-template'},

{slug:'can-landlord-enter-without-notice',title:'Can a Landlord Enter Without Notice? State-by-State Rules',
desc:'Most states require 24–48 hours notice before a landlord enters. Learn the rules for all 50 states, emergency exceptions, and tenant rights.',
intro:'Unauthorized landlord entry is one of the most common tenant complaints — and one of the most misunderstood areas of landlord-tenant law.',
secs:[
{h:'The General Rule: 24–48 Hours Notice Required',p:['The majority of US states require landlords to give <strong>24 hours</strong> advance written notice before entering a rental unit for non-emergency purposes (inspections, repairs, showings). States requiring 24-hour notice include: California, Florida, New York, Texas (no specific requirement, but reasonable notice applies), Illinois, and most others.',
'States requiring <strong>48 hours</strong> notice: New Hampshire, Vermont, Wisconsin, Maine. Most states allow entry only during <strong>reasonable hours</strong> — typically business hours, Monday through Friday 8AM–6PM, unless the tenant agrees otherwise.']},
{h:'What Counts as an Emergency (No Notice Required)',p:['All states allow landlords to enter without notice in genuine emergencies: fire, flood, burst pipes, gas leak, suspected break-in, or any situation that poses an immediate threat to the property or the safety of occupants.',
'Important: the landlord must genuinely believe an emergency exists. Using "emergency" as a pretext to enter without notice for a non-emergency purpose is an illegal entry. If a landlord enters claiming an emergency but there clearly wasn\'t one, it can be treated as a harassment or illegal entry.']},
{h:'Permitted Purposes for Entry',p:['Even with proper notice, landlords can only enter for specific purposes: making repairs or inspections, showing the unit to prospective tenants or buyers, evaluating the unit after the tenant has given notice to vacate, responding to a court order, or in emergencies.',
'Landlords cannot use their key to enter simply because they own the property. Tenants have a right to "quiet enjoyment" — peaceful use of the rental without undue interference from the landlord.']},
{h:'Tenant Rights When a Landlord Enters Illegally',p:['If a landlord enters without proper notice or for unauthorized purposes, tenants have remedies: (1) <strong>Written demand</strong> — send a letter documenting the unauthorized entry and demanding it stop. (2) <strong>Complaint to housing authority</strong> — many cities have tenant affairs offices that investigate unauthorized entry complaints. (3) <strong>Lawsuit for damages</strong> — California, for example, allows tenants to sue for actual damages or $100 per violation, plus attorney\'s fees. (4) <strong>Lease termination</strong> — repeated unauthorized entries may constitute a breach of the covenant of quiet enjoyment, allowing the tenant to terminate and sue for constructive eviction.']}
],
faqList:[
{q:'Does a landlord need notice to enter for repairs they scheduled?',a:'Yes. Even if the landlord previously told you a repair person would come "sometime next week," a specific written notice (typically 24 hours before) is still required in most states. General advance notice of upcoming maintenance doesn\'t satisfy the entry notice requirement.'},
{q:'Can a tenant refuse a landlord\'s entry?',a:'A tenant can refuse entry if the landlord did not provide legally required notice, if the landlord is entering at an unreasonable hour, or if the purpose of entry is not legally permitted. Tenants should be cautious about refusing entry for legitimate repair needs — repeated refusals can be a lease violation.'},
{q:'Can a landlord show the unit to buyers without notice?',a:'No. Showing the unit to prospective buyers or tenants requires the same advance notice as any other entry — 24–48 hours in most states. During the final months of a fixed-term lease, some states reduce this to 24 hours and limit showings to reasonable hours.'},
{q:'What if the lease says the landlord can enter anytime?',a:'Such a clause is void in most states. Tenant right-to-notice protection is created by statute and cannot be waived by lease agreement. A landlord who enters in violation of the statutory requirement has committed an illegal entry regardless of what the lease says.'}
],
ctaTxt:'Create a lease agreement with proper entry notice clause — free',ctaHref:'/lease-agreement-template'},

{slug:'how-to-dissolve-an-llc',title:'How to Dissolve an LLC: Step-by-Step Guide (2026)',
desc:'Closing your LLC correctly protects you from future liability. Learn the dissolution steps, state filing requirements, and tax obligations.',
intro:'Not closing an LLC properly is one of the most common and expensive mistakes small business owners make — the LLC keeps accruing annual fees, taxes, and potential liability even after you stop operating.',
secs:[
{h:'Step 1: Vote to Dissolve',p:['Check your LLC operating agreement — most require a majority vote (or supermajority) of members to approve dissolution. Document the vote in writing: a "resolution to dissolve" signed by the requisite number of members. For single-member LLCs, the sole member\'s written decision is sufficient.',
'Once the vote is documented, set an effective dissolution date and stop taking on new business obligations.']},
{h:'Step 2: Wind Up Business Affairs',p:['Before filing dissolution with the state, you must "wind up" the LLC: (1) Complete all pending contracts or formally terminate them. (2) Collect all outstanding accounts receivable. (3) Pay all outstanding debts and obligations — including employee wages, vendor bills, taxes. (4) Notify creditors of the dissolution (some states require a formal creditor notice period of 90–180 days). (5) Close business bank accounts and credit cards after all checks clear.',
'Priority of payments: creditors are paid before members receive any distributions. Paying member distributions before paying creditors can expose members to personal liability for the shortfall.']},
{h:'Step 3: File Articles of Dissolution with Your State',p:['Every state requires a formal dissolution filing with the Secretary of State (or equivalent agency). The document is typically called "Articles of Dissolution," "Certificate of Termination," or "Statement of Dissolution." Filing fees range from $0 (Iowa) to $200 (California).',
'Required information: LLC name and state ID number, effective date of dissolution, confirmation that debts have been paid, and member/manager signatures. Some states also require a tax clearance certificate from the state revenue department before accepting the dissolution filing.']},
{h:'Step 4: Handle Final Tax Filings',p:['File a final federal tax return for the LLC (check "final return" on the form). If you have employees, file all final payroll tax returns and W-2s. Close the business\'s EIN by sending a letter to the IRS. If your LLC was registered in multiple states, file dissolution in every state where you were registered.',
'Keep business records for at least 7 years after dissolution — IRS audit windows and state audit periods can extend that long. Records include the articles of dissolution, the final tax returns, member voting records, and all financial statements.']}
],
faqList:[
{q:'What happens if I just stop operating my LLC without dissolving it?',a:'The LLC continues to exist legally. You continue to owe annual report fees, franchise taxes, and registered agent fees. The state can administratively dissolve the LLC for non-payment — but even then, you may still be liable for taxes owed during the period before dissolution. Failing to dissolve properly also keeps the LLC vulnerable to lawsuits related to past activities.'},
{q:'Can I dissolve an LLC with outstanding debt?',a:'You can file for dissolution while debts exist, but the winding-up process requires paying known creditors before distributing assets to members. If the LLC is insolvent (debts exceed assets), consult a business attorney before dissolving — members and managers who distribute assets to themselves before paying creditors can face personal liability for the shortfall.'},
{q:'How long does LLC dissolution take?',a:'Processing time varies significantly by state: California 1–2 weeks, Delaware 24 hours (expedited), Texas 2–4 weeks, New York 3–6 weeks, Florida 5–7 business days. Expedited filing options are available in most states for a higher fee. After the state approves dissolution, the LLC is terminated.'},
{q:'Do I need a lawyer to dissolve an LLC?',a:'For a simple LLC with one or two members, few assets, and no outstanding disputes, self-filing dissolution is generally straightforward. For LLCs with multiple members who disagree, significant assets to distribute, employees, ongoing contracts, or substantial debt, consulting a business attorney is strongly recommended to avoid personal liability exposure.'}
],
ctaTxt:'Create a free LLC operating agreement for your next business',ctaHref:'/llc-operating-agreement-template'},

{slug:'commercial-lease-vs-residential-lease',title:'Commercial Lease vs Residential Lease: 7 Key Differences',
desc:'Commercial leases give tenants far fewer protections than residential leases. Learn the 7 biggest differences before signing.',
intro:'Signing a commercial lease without understanding how it differs from a residential lease is one of the most expensive mistakes a small business owner can make.',
secs:[
{h:'1. Consumer Protection Laws Don\'t Apply',p:['Residential leases are governed by state landlord-tenant statutes that protect tenants — security deposit limits, entry notice requirements, habitability warranties, and eviction procedures. Commercial leases are contract law — whatever the parties agree to is generally enforceable, period.',
'A commercial landlord can contractually require you to pay the landlord\'s attorney\'s fees if you lose a lawsuit, maintain the entire building\'s HVAC system, or carry $5 million in liability insurance. In a residential lease, such clauses would be void.']},
{h:'2. Everything Is Negotiable — And Expected to Be',p:['Commercial landlords expect tenants to negotiate. The first draft of a commercial lease is always favorable to the landlord. Typical negotiation points: free rent period during build-out, tenant improvement allowance (TI allowance — how much the landlord contributes to renovations), personal guarantee limitations, assignment and subletting rights, and renewal option terms.',
'Getting a commercial real estate attorney or tenant rep broker is strongly advisable — they pay for themselves in the savings they negotiate.']},
{h:'3. Triple Net (NNN) vs Gross Leases',p:['Most commercial leases are structured as a <strong>gross lease</strong> (tenant pays one flat amount, landlord pays operating expenses) or a <strong>triple net lease (NNN)</strong> (tenant pays base rent PLUS a pro-rated share of property taxes, building insurance, and common area maintenance — CAM charges). In a full NNN lease, the tenant bears nearly all building operating costs in addition to base rent.',
'CAM charges can be substantial and unpredictable — budget 20–40% on top of base rent for NNN leases in retail and industrial properties. Always cap CAM charge increases and audit the landlord\'s CAM calculations annually.']},
{h:'4. Personal Guarantees Are Common',p:['Commercial landlords routinely require the principals of a tenant LLC or corporation to personally guarantee the lease. This pierces the corporate veil — if your business fails, you are personally liable for remaining rent through the lease term.',
'Negotiation tactics: (1) Limit the guarantee to 12–18 months of base rent rather than the full lease term. (2) "Burn-off" clause — the guarantee reduces over time as you demonstrate consistent payment. (3) Good-guy clause — the guarantor is released from future liability if they give prompt notice and vacate voluntarily when the business can\'t pay.']}
],
faqList:[
{q:'Is there a security deposit limit for commercial leases?',a:'No. Commercial lease security deposits have no statutory limit — they are set by negotiation. Three to six months of base rent is common for new businesses without a track record. Established businesses with good credit may negotiate lower deposits. The deposit is typically not held in a separate trust account (unlike residential deposits in most states).'},
{q:'Does a commercial tenant have a right to quiet enjoyment?',a:'Yes, but the scope is defined by the lease, not by statute. A commercial lease should include an express quiet enjoyment covenant. Unlike residential tenants, commercial tenants typically cannot rely on implied warranty of habitability — if you need the space to be in a particular condition, spell it out in the lease.'},
{q:'Can a commercial landlord evict faster than a residential landlord?',a:'Generally yes. Commercial evictions follow the same notice-and-court process, but courts typically move faster, tenant defenses are narrower, and there are no restrictions on lockouts in some states for commercial properties. California, for example, allows commercial landlords to use "self-help" eviction (changing locks) in certain circumstances — which is illegal for residential tenants.'},
{q:'What is a "co-tenancy" clause in a commercial lease?',a:'A co-tenancy clause (common in retail shopping center leases) gives the tenant the right to reduce rent or terminate the lease if an anchor tenant (like a major department store) leaves the center. This protects the small retailer whose foot traffic depends on the anchor. Co-tenancy clauses are heavily negotiated and often fought by landlords.'}
],
ctaTxt:'Create a free commercial lease agreement',ctaHref:'/commercial-lease-template'},

{slug:'power-of-attorney-for-elderly-parent',title:'How to Get Power of Attorney for an Elderly Parent',
desc:'Step-by-step guide to obtaining power of attorney for an aging parent — while they are still able to grant it. What to do if they can\'t.',
intro:'The most important thing to know: a power of attorney can only be granted by someone who is mentally competent. If you wait until your parent has dementia, it may be too late.',
secs:[
{h:'Why Timing Is Everything',p:['A power of attorney requires the principal to have legal capacity — they must understand what they are signing, what authority they are giving, and to whom. Early-stage dementia often does not eliminate capacity; it is a spectrum. But as dementia progresses, there comes a point where a court would not recognize any POA signed after that threshold.',
'The family conversation about POA is uncomfortable. It feels like planning for decline. But the cost of not having a POA — court-ordered conservatorship — is far higher: $5,000–$30,000+ in legal fees, months of delay, and a judge making decisions instead of your family.']},
{h:'Which Type of POA Does an Elderly Parent Need?',p:['For most aging parents, you need two documents: (1) A <strong>Durable Financial POA</strong> — authorizes a child or trusted person to manage bank accounts, pay bills, file taxes, manage investments, and handle real estate. "Durable" means it remains effective if the parent becomes incapacitated. (2) A <strong>Healthcare (Medical) POA</strong> — authorizes someone to make medical decisions, choose providers, access medical records (HIPAA), and make end-of-life decisions if the parent cannot.',
'These should be accompanied by a <strong>living will (advance directive)</strong> stating the parent\'s own wishes about life support, CPR, and feeding tubes — so the healthcare agent knows what the parent would want.']},
{h:'How to Prepare and Execute the Documents',p:['Most states provide forms or templates for both a financial and healthcare POA. Steps: (1) Prepare the documents with your parent — do not prepare them without their involvement and genuine consent. (2) Have an attorney review if there are complex assets or family disputes. (3) Sign before a notary public. (4) Most states also require 1–2 witnesses (who cannot be the agent, their spouse, or a beneficiary of the parent\'s estate). (5) Give copies to the agent, successor agents, the parent\'s primary care physician, and all financial institutions involved.',
'For healthcare POA specifically: deliver a copy to the parent\'s primary care doctor, any specialist, and the hospital system where they typically receive care. Register it if your state has a healthcare directive registry.']},
{h:'What If Your Parent Can\'t Sign a POA?',p:['If a parent has already lost mental capacity, no POA can be signed. The family\'s only option is a court-ordered <strong>guardianship or conservatorship</strong>. In guardianship, the court appoints someone to make personal and medical decisions. In conservatorship, the court appoints someone to manage finances.',
'This process takes 2–6 months, costs $5,000–$30,000+ in legal fees, requires an attorney in most states, involves a court investigator visiting the parent, and results in annual court reporting requirements. The conservator must account to the court for every financial decision. It is avoidable with timely POA planning.']}
],
faqList:[
{q:'Can a parent with early dementia still sign a POA?',a:'Possibly — it depends on whether they have "testamentary capacity" at the time of signing. Courts look at: does the person understand what a POA is, who they are appointing, and what authority they are giving? Early dementia may not eliminate this capacity. A physician\'s letter documenting capacity at the time of signing (even with a diagnosis) greatly strengthens the POA\'s validity.'},
{q:'Can siblings challenge a POA?',a:'Yes. A sibling who believes the parent lacked capacity, was unduly influenced, or was defrauded when signing the POA can file a legal challenge. This is why having the POA signed with witnesses, in front of a notary, and with a physician capacity letter is so important. The more documentation of knowing, voluntary consent, the harder the challenge.'},
{q:'What authority does a financial POA give my child over my accounts?',a:'A durable financial POA typically authorizes the agent to: access and manage all bank accounts, pay bills, file tax returns, buy and sell real estate, manage investments, apply for benefits, and operate a business. You can limit the scope — for example, authorizing bill pay only, not real estate transactions. Be specific about any limitations.'},
{q:'Is a POA from another state valid?',a:'Generally yes. Most states have laws recognizing POAs executed in other states if valid under that state\'s law at the time of signing. However, some financial institutions are skeptical of out-of-state POAs and may require their own forms. Always call ahead before trying to use an out-of-state POA for a major transaction.'}
],
ctaTxt:'Create a free power of attorney — all types',ctaHref:'/power-of-attorney-template'},

{slug:'joint-tenancy-vs-tenancy-in-common',title:'Joint Tenancy vs Tenancy in Common: What\'s the Difference?',
desc:'Two people can own property together in very different ways. Joint tenancy vs tenancy in common — survivorship rights, sale rights, and estate planning.',
intro:'How you hold title to real property with another person determines what happens when one owner dies, wants to sell, or gets divorced. Getting it wrong has major consequences.',
secs:[
{h:'Joint Tenancy With Right of Survivorship',p:['In a joint tenancy, two or more people own equal shares of a property, and when one owner dies, their share automatically passes to the surviving owner(s) — bypassing probate entirely. The surviving owner receives the deceased owner\'s share by operation of law, simply by recording a death certificate.',
'Requirements for creating a joint tenancy: all owners must acquire title at the same time, through the same deed, with equal shares, and with the right of survivorship explicitly stated in the deed. Missing any of these requirements typically creates a tenancy in common instead.']},
{h:'Tenancy in Common',p:['In a tenancy in common, two or more people own a property with defined percentage interests (which can be unequal), and each owner\'s share passes through their estate when they die — it goes to whoever they name in their will (or to heirs under intestate succession if there is no will), not automatically to the other owners.',
'A tenancy in common owner can sell or mortgage their individual share without the other owners\' consent (though a buyer of a partial interest rarely wants to own property with strangers). This is the default form of co-ownership when the deed does not specify.']},
{h:'Which Is Better for Married Couples?',p:['Many married couples hold property as joint tenants so that on the first spouse\'s death, the surviving spouse automatically owns the entire property without probate. Simple and fast.',
'However, in community property states (Arizona, California, Idaho, Louisiana, Nevada, New Mexico, Texas, Washington, Wisconsin), married couples often hold property as "community property with right of survivorship" — which gives both the automatic survivorship of joint tenancy and the tax advantage of community property (full step-up in cost basis on the first death, saving capital gains tax when the survivor sells).']},
{h:'Severing a Joint Tenancy',p:['A joint tenancy can be "severed" (converted to a tenancy in common) by one owner transferring their share — even to themselves via a deed to a trustee, in some states. Once severed, the survivorship feature disappears. This is sometimes used in estate planning to ensure a share goes to children from a prior marriage rather than automatically to a spouse.',
'A tenancy in common can be converted to joint tenancy only if all owners agree and execute a new deed explicitly creating joint tenancy with right of survivorship.']}
],
faqList:[
{q:'Can joint tenancy owners be forced to sell?',a:'A joint tenant who wants to sell but cannot get the other tenant\'s agreement can file a "partition action" in court. The court can either order the property divided (partition in kind) or order it sold with proceeds split proportionally (partition by sale). Partition actions are costly and take 1–2 years — an exit strategy clause in a co-ownership agreement is far better.'},
{q:'What happens to a joint tenancy in a divorce?',a:'In most states, divorce automatically severs a joint tenancy and converts it to a tenancy in common — preventing the "accidental inheritance" of the property by an estranged spouse. The divorce settlement agreement or court order then determines what happens to the tenants-in-common shares.'},
{q:'Can a tenant in common leave their share to whoever they want?',a:'Yes. Unlike a joint tenant (whose share passes to the surviving co-owner automatically), a tenant in common can leave their share to anyone via their will. If they die without a will, the share passes to heirs under intestate succession law — not necessarily the other owners.'},
{q:'Should unmarried co-buyers use joint tenancy or tenancy in common?',a:'Unmarried co-buyers (partners, friends, siblings) usually benefit from tenancy in common with a co-ownership agreement that specifies: what percentage each person owns, how expenses are split, what happens if one wants to sell or refinance, and a right of first refusal (the other owner gets to buy out the selling owner before they sell to a stranger).'}
],
ctaTxt:'Transfer property correctly — free quitclaim deed template',ctaHref:'/quitclaim-deed-template'},

{slug:'what-is-a-cease-and-desist-letter',title:'What Is a Cease and Desist Letter? How to Write One That Works',
desc:'A cease and desist letter is a demand to stop harmful behavior. Learn when it is effective, what to include, and when to escalate to court.',
intro:'A cease and desist letter is not a court order — it is a formal demand. Its power lies in credibility: it signals you are serious, documents the violation, and creates a record before litigation.',
secs:[
{h:'When to Use a Cease and Desist Letter',p:['Common situations: (1) <strong>Copyright infringement</strong> — someone is using your photos, writing, or creative work without permission. (2) <strong>Trademark infringement</strong> — a business is using your brand name, logo, or a confusingly similar one. (3) <strong>Defamation</strong> — false statements of fact are being made about you or your business. (4) <strong>Harassment or stalking</strong>. (5) <strong>Breach of contract</strong> — a former employee is violating a non-compete or NDA.',
'A cease and desist letter is most effective when the recipient has something to lose by continuing the behavior — business reputation, a professional license, or facing imminent litigation. It is less effective against anonymous online harassers or judgment-proof defendants.']},
{h:'What a Cease and Desist Letter Must Include',p:['An effective cease and desist letter includes: (1) Your identity and the specific legal right being violated. (2) A precise description of the violation — dates, locations, URLs, specific acts. (3) The specific demand — stop the activity by [date], remove the infringing content, destroy infringing copies, etc. (4) A response deadline — typically 10–14 business days. (5) The legal consequences if demands are not met — lawsuit, injunction, damages. (6) A statement that the letter is being kept as evidence.',
'Tone should be firm and factual, not emotional or threatening beyond legitimate legal consequences. Threatening criminal prosecution for a civil matter, or making demands you have no legal basis for, can backfire — and in some states, an abusive demand letter can itself be grounds for a malicious prosecution counterclaim.']},
{h:'Does It Have to Come from a Lawyer?',p:['No. Anyone can send a cease and desist letter. A letter on attorney letterhead carries more psychological weight — recipients tend to take it more seriously. But a well-written letter from an individual can be just as legally significant: it documents notice, establishes the timeline, and forces the recipient to respond.',
'For high-stakes situations (significant infringement, business-threatening defamation, large contract breaches), an attorney-drafted letter is worth the investment. For smaller matters, a well-documented self-written letter is a reasonable first step.']},
{h:'What Happens After You Send It',p:['Three possible responses: (1) The recipient complies — they stop the behavior, respond with a settlement offer, or simply go quiet. This is the desired outcome and happens more often than people expect. (2) The recipient disputes your claim in writing — their response may reveal weaknesses in your position and open a dialogue. (3) The recipient ignores it or escalates — in this case, your letter becomes exhibit A in your subsequent lawsuit.',
'Keep a copy of the letter, the date sent, proof of delivery (certified mail or email read receipt), and any response. If you need to go to court, this documentation is critical.']}
],
faqList:[
{q:'Is a cease and desist letter legally binding?',a:'No. A cease and desist letter is a demand, not a court order. The recipient is not legally required to comply. However, ignoring it and continuing the behavior can be used as evidence of willful infringement or bad faith — which increases damages in subsequent litigation. For a legally binding stop order, you must obtain a court-issued injunction.'},
{q:'Can sending a cease and desist letter backfire?',a:'Yes. If your legal claim is weak or unsupported, the recipient may countersue for wrongful use of legal process. Public figures sometimes "Streisand Effect" a cease and desist — sending it generates publicity that draws far more attention to the issue than the original violation. Evaluate whether sending one serves your actual goals before proceeding.'},
{q:'How long does a cease and desist letter take to work?',a:'If it works, typically within the 10–14 day response window. Some recipients comply immediately; others negotiate. If the recipient is a business worried about its reputation or legal costs, response can come within days.'},
{q:'Can I send a cease and desist for online defamation?',a:'Yes, and it\'s often the first step. Include: the exact false statements, where they were published (URLs, dates), and why they are false and defamatory. Request removal and retraction. If the content is on a platform, also file a platform takedown request simultaneously — defamation reports on Google, Yelp, Facebook, etc. are evaluated separately from your letter to the poster.'}
],
ctaTxt:'Create a free cease and desist letter',ctaHref:'/cease-and-desist-template'},

{slug:'how-to-write-a-demand-letter',title:'How to Write a Demand Letter: Template, Format & Tips',
desc:'A demand letter is the first step before suing. Learn the required elements, the right tone, and a format that courts take seriously.',
intro:'A well-written demand letter can resolve a dispute without going to court — and if you do need to sue, it shows the judge you tried to resolve it first.',
secs:[
{h:'What a Demand Letter Is For',p:['A demand letter formally notifies someone that they owe you money, have violated a contract, caused you harm, or need to take a specific action — and gives them a deadline to respond before you take legal action. Courts in most states require evidence that you attempted to resolve a dispute before filing, and a demand letter satisfies this requirement.',
'Common uses: unpaid invoices, security deposit disputes, personal injury claims, breach of contract (contractor didn\'t finish work, business partner didn\'t pay), property damage, and landlord-tenant disputes.']},
{h:'Required Elements',p:['Every demand letter should include: (1) Your full name and contact information at the top. (2) The recipient\'s full name and address. (3) The date. (4) A clear statement of what happened — the facts, in chronological order, without editorializing. (5) The specific legal basis if applicable ("This constitutes breach of contract under our agreement dated March 1, 2026"). (6) The exact amount or action demanded. (7) A specific deadline — typically 14–30 days. (8) A statement of next steps if demands are not met: "If I do not receive payment by [date], I will file a claim in [court] without further notice."',
'Sign the letter and keep a copy. Send via certified mail return receipt requested, and also email if you have the address — multiple delivery methods create a stronger paper trail.']},
{h:'Tone and Language',p:['Effective demand letters are: factual, specific, and free of emotional language. "You stole from me and you\'re a liar" is less effective than "As documented in invoices 101–103, a total of $4,750 remains outstanding past the 30-day payment term in our agreement."',
'Avoid: threats of criminal prosecution for civil matters (this can constitute extortion in some states), vague threats ("take all legal action available"), or negotiating against yourself by starting at a lower number than you\'re owed. Demand the full amount you are owed.']},
{h:'Small Claims vs. Demand Letter',p:['For disputes under $5,000–$25,000 (limits vary by state), small claims court is designed for self-represented parties. The demand letter is still important — many small claims courts require proof that you demanded payment before filing, and some defendants will pay after receiving the letter rather than face court.',
'For amounts over the small claims limit, you will need a lawyer or represent yourself in regular civil court. The demand letter establishes the timeline, documents the amount, and demonstrates good faith — all of which matter to a judge.']}
],
faqList:[
{q:'Does a demand letter need to be from a lawyer?',a:'No. Anyone can write and send a demand letter. Letters on attorney letterhead are often taken more seriously by businesses and insurance companies, but a well-documented letter from an individual is fully effective. For amounts under $5,000, writing it yourself is almost always cost-effective.'},
{q:'What if the recipient ignores my demand letter?',a:'File in small claims court (for amounts under your state\'s limit) or hire an attorney for larger claims. The demand letter becomes evidence that you notified the defendant of the claim and gave them an opportunity to resolve it before litigation — judges appreciate this.'},
{q:'Should I send the demand letter by email or certified mail?',a:'Both if possible. Certified mail with return receipt creates a legal record that the letter was delivered and signed for. Email creates a timestamp showing delivery. If the recipient claims they never received the letter, you have two forms of delivery evidence.'},
{q:'Can a demand letter be used against me?',a:'Your letter can be read in court, so be accurate. Do not overstate your damages, claim injuries that didn\'t happen, or threaten actions you won\'t take. Courts can use exaggerated demand letters to undermine your credibility.'}
],
ctaTxt:'Create a free cease and desist or demand letter',ctaHref:'/cease-and-desist-template'},

{slug:'llc-vs-sole-proprietorship',title:'LLC vs Sole Proprietorship: Which Is Better for Your Business?',
desc:'The key difference: an LLC protects your personal assets from business debts; a sole proprietorship doesn\'t. When each makes sense.',
intro:'The most important question isn\'t tax treatment — it\'s personal liability. If your business gets sued or can\'t pay its debts, do you want to lose your house?',
secs:[
{h:'Personal Liability: The Core Difference',p:['A <strong>sole proprietorship</strong> is the simplest business structure — you and your business are legally the same entity. Business debts are your personal debts. If your business is sued and loses, the plaintiff can go after your personal bank accounts, car, and home.',
'An <strong>LLC (Limited Liability Company)</strong> creates a legal wall between you and the business. If the LLC is sued or can\'t pay its debts, creditors can only go after LLC assets — not your personal assets. This is the primary reason to form an LLC. The protection is not absolute (courts can "pierce the corporate veil" if you comingle personal and business funds or treat the LLC as your alter ego), but it is significant.']},
{h:'Tax Treatment',p:['Both sole proprietorships and single-member LLCs are taxed as "pass-through" entities by default — business income flows to your personal tax return (Schedule C) and you pay self-employment tax (15.3% on net profit up to the Social Security wage base in 2026).',
'The difference: an LLC can elect S-Corp tax treatment, allowing you to split income between a salary and distributions. Distributions are not subject to self-employment tax. This can save $5,000–$20,000+ per year for profitable businesses. This election makes sense roughly when net profit consistently exceeds $50,000–$60,000/year.']},
{h:'Cost and Complexity',p:['A sole proprietorship has zero formation cost and zero ongoing compliance requirements. You just start operating. There\'s nothing to file, no annual reports, and no fees (unless you file a DBA).',
'An LLC requires: state filing fee ($50–$500 depending on state), registered agent (you or a service), operating agreement, separate bank account, and in many states an annual report and fee. California adds an $800/year minimum franchise tax. Delaware LLCs pay $300/year. New York adds a publication requirement that can cost $1,000+.']},
{h:'When to Use Each',p:['<strong>Sole proprietorship makes sense</strong> for: very low-risk service businesses (consulting, freelancing with low liability exposure), testing a business idea before committing, or businesses with very low annual net income where LLC costs aren\'t worth it.',
'<strong>LLC makes sense</strong> for: any business that could be sued (services where you give advice, physical goods, client-facing work), businesses with real assets (equipment, inventory, IP), any business with employees, businesses where personal liability protection justifies the cost, and any business earning consistently over $50K/year (where S-Corp election can save on taxes).']}
],
faqList:[
{q:'Can I convert from a sole proprietorship to an LLC?',a:'Yes. File LLC articles of organization with your state, get a new EIN from the IRS, open a new business bank account, and transfer contracts and assets to the LLC. Notify clients, vendors, and your bank. The conversion is prospective — you cannot retroactively protect yourself from past sole proprietorship debts.'},
{q:'Does an LLC protect me from my own negligence?',a:'An LLC protects you from business debts and lawsuits arising from the business\'s operations or the negligence of employees. It does NOT protect you from your own personal negligence — if you personally cause harm (run a red light in the company van, give bad advice to a client), you can still be personally liable. Professional liability insurance covers this gap.'},
{q:'Do I need a business license for either?',a:'Business structure (LLC vs sole proprietorship) is separate from licensing. Most businesses need some combination of local business license, professional license, seller\'s permit, or industry-specific permits regardless of structure. Check your city, county, and state requirements.'},
{q:'Which is better for a side hustle?',a:'For a very small side hustle with low liability risk (selling on Etsy, writing, design), sole proprietorship is fine. Once income exceeds $10,000/year or the nature of the work creates liability exposure (physical products, advice, services where errors harm clients), the LLC\'s protection is worth the cost.'}
],
ctaTxt:'Create your free LLC operating agreement',ctaHref:'/llc-operating-agreement-template'},

{slug:'what-to-include-in-a-freelancer-contract',title:'What to Include in a Freelancer Contract (2026 Checklist)',
desc:'A freelancer contract protects both the client and the freelancer. Learn the 8 clauses every independent contractor agreement needs.',
intro:'Handshake deals in freelancing lead to scope creep, late payments, and ownership disputes. A one-page contract prevents all three.',
secs:[
{h:'Scope of Work: The Most Important Clause',p:['The scope of work defines exactly what the freelancer will deliver and what they will not. This is the single most important clause because it defines "done" — the line between satisfactory completion and scope creep.',
'Be specific: not "a website" but "a 5-page responsive website including homepage, about, services, contact, and blog index page, built in WordPress with the provided theme, with 3 rounds of revisions." Specify what is excluded ("does not include SEO optimization, hosting setup, or stock photo licensing"). Every word you add to scope reduces future disputes.']},
{h:'Payment Terms',p:['Specify: rate (hourly or project-based), total amount, payment schedule (50% upfront, 50% on delivery is standard for new client relationships; milestones for longer projects), payment method (PayPal, bank transfer, check), invoice timing, and late payment penalty (typically 1.5% per month on overdue balances).',
'For ongoing retainer relationships: define the monthly retainer amount, what it covers (number of hours or deliverables), what is billed additionally, and the notice period to end the retainer.']},
{h:'Intellectual Property: Who Owns the Work?',p:['By default under US copyright law, an independent contractor retains ownership of the work they create — not the client. This means if you hire a freelancer without a written IP assignment, you may not legally own the website, logo, or code they built for you.',
'Your contract should include an IP assignment clause: "Upon receipt of full payment, Contractor assigns all intellectual property rights in the Work to Client." Alternatively, grant the client a license to use the work rather than full ownership (common for photographers and illustrators who retain copyright but license usage).']},
{h:'Termination, Revisions, and Disputes',p:['Termination: either party should be able to terminate with 14–30 days\' written notice. Include a kill fee clause — if the client cancels after work has begun, they pay a percentage of the remaining contract (typically 25–50%) to compensate the freelancer for the lost opportunity.',
'Revisions: specify how many revision rounds are included. "Unlimited revisions" is a trap — set a number (2–3) and define what constitutes a revision vs a new request. Disputes: include a governing state law clause and whether disputes go to arbitration or court. For small contracts, specifying the client\'s local small claims court is efficient.']}
],
faqList:[
{q:'Should a freelancer or the client draft the contract?',a:'Whoever sends the contract sets the baseline terms. Freelancers who send their own contract control the IP assignment language, revision limits, and payment terms. Clients who send the contract often include clauses requiring full IP assignment, unlimited revisions, and no kill fee. Having your own template ready and sending it first gives you negotiating leverage.'},
{q:'Is a verbal freelance agreement enforceable?',a:'Verbal contracts are generally enforceable for services, but proving what was agreed is extremely difficult. Courts in most states require written evidence for contracts over $500 (under the statute of frauds). More practically: if the scope, price, and IP ownership weren\'t written down, both parties will remember them differently the moment a dispute arises.'},
{q:'Can a client sue a freelancer for missing a deadline?',a:'Yes, if the deadline was a specified contract term. A freelancer who materially breaches by missing deadlines can be liable for the client\'s damages (costs of hiring someone else to finish, lost revenue if the delay caused measurable harm). Force majeure clauses (covering unavoidable delays) are worth including.'},
{q:'What is a "work made for hire" clause?',a:'Under copyright law, "work made for hire" applies automatically to employees — the employer owns the work. For independent contractors, it only applies to certain specific categories of work (contributions to collective works, motion pictures, translations, instructional texts, etc.) if there is a written agreement. For most freelance work, you need an explicit IP assignment clause — "work made for hire" alone doesn\'t do the job.'}
],
ctaTxt:'Create a free independent contractor agreement',ctaHref:'/independent-contractor-agreement-template'},

];

posts.forEach(function(p){
  fs.writeFileSync(B+p.slug+'.html', art(p.slug,p.title,p.desc,p.intro,p.secs,p.faqList,p.ctaTxt,p.ctaHref));
});
console.log('Blog batch 3: '+posts.length+' articles');
