const fs = require('fs');
const B = 'C:/Users/mastr/claude co/legal-docs/blog/';
fs.mkdirSync(B, {recursive:true});

var NAV = '<header class="site-header"><div class="header-inner"><a href="/" class="site-logo">FreeDoc<span>Templates</span></a><nav class="main-nav" aria-label="Main"><div class="nav-group"><button class="nav-trigger" aria-haspopup="true" aria-expanded="false">Templates <svg class="nav-chevron" width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" stroke-width="2"><path d="M2 4l4 4 4-4"/></svg></button><div class="nav-dropdown"><a href="/lease-agreement-template" class="nav-item">Lease Agreement</a><a href="/eviction-notice-template" class="nav-item">Eviction Notice</a><a href="/bill-of-sale-template" class="nav-item">Bill of Sale</a><a href="/quitclaim-deed-template" class="nav-item">Quitclaim Deed</a><a href="/power-of-attorney-template" class="nav-item">Power of Attorney</a></div></div></nav><div class="header-actions"><a href="/tools" class="btn-all-tools">All Templates</a><button id="btn-search" class="btn-search" aria-label="Search"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><path d="M21 21l-4.35-4.35"/></svg></button></div></div></header><div class="cmd-overlay" id="cmd-overlay"><div class="cmd-modal"><div class="cmd-header"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><path d="M21 21l-4.35-4.35"/></svg><input class="cmd-input" id="cmd-input" placeholder="Search templates\u2026" autocomplete="off"></div><div class="cmd-body" id="cmd-body"></div></div></div>';
var FTR = '<footer class="site-footer"><div class="container"><div class="footer-grid"><div><a href="/" class="footer-logo">FreeDocTemplates</a><p class="footer-tagline">Free legal document templates. No sign-up, no watermarks.</p></div><div><div class="footer-col-title">Templates</div><nav class="footer-nav"><a href="/lease-agreement-template">Lease Agreement</a><a href="/eviction-notice-template">Eviction Notice</a><a href="/quitclaim-deed-template">Quitclaim Deed</a><a href="/power-of-attorney-template">Power of Attorney</a></nav></div></div><div class="footer-bottom"><p>\u00a9 2026 FreeDocTemplates.xyz</p></div></div></footer>';

function wrap(title,desc,canon,body){return '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+'</title><meta name="description" content="'+desc+'"><link rel="canonical" href="https://www.freedoctemplates.xyz/blog/'+canon+'"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap"><link rel="stylesheet" href="/shared/styles.css?v=1"></head><body>'+NAV+'<main class="page-wrap">'+body+'</main>'+FTR+'<script src="/shared/scripts.js?v=1" defer><\/script></body></html>';}
function sec(h2,paras){return '<h2 style="font-size:20px;font-weight:700;color:var(--ink-1);margin:32px 0 12px">'+h2+'</h2>'+paras.map(function(p){return '<p style="color:var(--ink-2);line-height:1.75;margin-bottom:14px">'+p+'</p>';}).join('');}
function faqs(list){return '<section class="faq-section" style="margin:40px -24px 0;padding:48px 24px"><div class="faq-header"><p class="section-eyebrow">FAQ</p></div><div class="faq-list">'+list.map(function(f){return '<details class="faq-item"><summary class="faq-q">'+f.q+'</summary><div class="faq-a">'+f.a+'</div></details>';}).join('')+'</div></section>';}
function cta(text,href){return '<div style="background:var(--surface-2);border:1px solid var(--border);border-radius:12px;padding:24px;text-align:center;margin:32px 0"><p style="font-weight:600;color:var(--ink-1);margin-bottom:10px">'+text+'</p><a href="'+href+'" style="display:inline-block;padding:11px 26px;background:var(--accent);color:#fff;border-radius:8px;font-weight:600;text-decoration:none">Get Free Template &#8594;</a></div>';}
function art(slug,title,desc,intro,secs,faqList,ctaTxt,ctaHref){var body='<div class="container"><nav class="breadcrumb"><a href="/">Home</a><span>&#8250;</span><a href="/blog">Blog</a><span>&#8250;</span><span aria-current="page">'+title+'</span></nav><h1 class="page-title" data-enter>'+title+'</h1><p class="page-sub" data-enter data-delay="1">'+intro+'</p></div><div class="container" style="max-width:760px;margin-top:32px">'+secs.map(function(s){return sec(s.h,s.p);}).join('')+cta(ctaTxt,ctaHref)+faqs(faqList)+'</div>';return wrap(title+' | FreeDocTemplates',desc,slug,body);}

var posts=[

{slug:'how-to-register-an-llc',title:'How to Register an LLC: Step-by-Step (2026)',
desc:'A complete walkthrough for forming an LLC — choose a state, file articles of organization, get an EIN, and open a business bank account.',
intro:'Forming an LLC takes about 1–2 hours online and costs $50–$500 depending on your state. Here\'s the exact sequence.',
secs:[
{h:'Step 1: Choose Your State',p:['Most businesses should form their LLC in the state where they operate. The myth of Delaware or Wyoming for small businesses: yes, those states have favorable laws for large corporations — but a small LLC operating in Texas that forms in Delaware must still register as a "foreign LLC" in Texas and pay Texas filing fees. You end up paying both states. Form in your home state unless you have specific reasons not to.',
'Exception: if you have significant outside investors, plan to raise venture capital, or will be issuing complex equity structures, Delaware\'s legal predictability (Court of Chancery, well-established case law) may be worth it.']},
{h:'Step 2: Name Your LLC',p:['Your LLC name must: (1) Include "LLC," "L.L.C.," "Limited Liability Company," or an accepted abbreviation. (2) Be distinguishable from existing business names in your state (check the Secretary of State\'s online name database). (3) Not use restricted words (Bank, Insurance, Attorney, etc.) without special approval.',
'Reserve the name if your state offers it ($10–$50 for 30–120 days) while you prepare your filing. Also secure the domain name and social media handles before filing — the name is worthless if the domain is taken.']},
{h:'Step 3: File Articles of Organization',p:['File with your state\'s Secretary of State (or equivalent — in some states it\'s the Department of State or Division of Corporations). Most states now accept online filing. You\'ll need: LLC name, registered agent name and address (a person or company that receives legal mail on behalf of the LLC), the principal business address, and the names of members or managers.',
'Filing fees: Wyoming $100, Colorado $50, Florida $125, Texas $300, California $70 (but then $800/yr minimum franchise tax), New York $200 (but then a $1,000+ publication requirement). Your articles are approved instantly or within 1–10 business days depending on state.']},
{h:'Step 4: EIN, Bank Account, and Operating Agreement',p:['<strong>EIN</strong>: Apply for an Employer Identification Number from the IRS at irs.gov — it\'s free and instant. You need it to open a business bank account, hire employees, and file business taxes. Even single-member LLCs should get an EIN to avoid using their Social Security number on vendor forms.',
'<strong>Bank account</strong>: Never mix personal and business funds. Open a dedicated business checking account using your LLC\'s name, articles of organization, and EIN. Commingling is the #1 reason courts pierce the corporate veil. <strong>Operating agreement</strong>: Draft and sign an operating agreement even if your state doesn\'t require one — it proves the LLC is a separate, legitimate entity.']}
],
faqList:[
{q:'Can I form an LLC without a lawyer?',a:'Yes. Online LLC formation is straightforward in most states. For a standard single-member or simple two-member LLC, DIY filing with a well-drafted operating agreement is sufficient. For complex multi-member LLCs, family business structures, or LLCs with outside investment, an attorney\'s guidance on the operating agreement is worth the cost.'},
{q:'How long does LLC formation take?',a:'Online filing approval times: Wyoming and Delaware — 24 hours; Florida, Colorado, Texas — 1–5 business days; California — 5–10 business days; New York — 1–2 weeks. Expedited filing for a higher fee is available in most states (Delaware can be same-day).'},
{q:'What is a registered agent?',a:'A registered agent is a person or company with a physical street address in the LLC\'s state who receives official legal documents (lawsuits, state notices) on behalf of the LLC during business hours. You can be your own registered agent if you have a physical address (not a PO box) in the state. Registered agent services cost $50–$150/year.'},
{q:'Do I need a business license in addition to an LLC?',a:'Yes. An LLC is a legal structure, not a business license. You still need applicable local business licenses, professional licenses, sales tax permits, and industry-specific permits to operate legally. Check your city, county, and state requirements — these are separate from the LLC formation filing.'}
],
ctaTxt:'Create your free LLC operating agreement',ctaHref:'/llc-operating-agreement-template'},

{slug:'roommate-agreement-what-to-include',title:'Roommate Agreement: What to Include (Complete Checklist)',
desc:'A roommate agreement prevents the most common shared-housing disputes — bills, guests, chores, and moving out. Free template with all key clauses.',
intro:'The #1 mistake new roommates make: assuming they agree on everything because they get along. A 15-minute conversation producing a one-page agreement prevents months of tension.',
secs:[
{h:'Rent and Utilities: Exact Amounts, Not Percentages',p:['The agreement must specify each roommate\'s exact share of rent in dollars — not percentages. If rent changes or a roommate leaves, "each person pays their share" becomes meaningless. Write: "Roommate A pays $900 toward rent; Roommate B pays $750 toward rent." Also specify who makes the payment to the landlord (usually one person collects from all and makes one payment).',
'For utilities: assign exact splits or assign bills. "Roommate A pays electric; Roommate B pays internet; all others split equally" is clearer than "we\'ll figure it out." Specify payment deadline — by the 1st of each month, with 3 days grace, or you cover that roommate\'s share and they reimburse you within 7 days.']},
{h:'Guests and Overnight Visitors',p:['Guest policies are the most common source of roommate tension. Define: how many consecutive nights a guest can stay (3–5 nights per month is standard), whether significant others are considered guests or semi-permanent residents after a certain threshold (30+ nights/year in some agreements triggers "guest becomes de facto roommate and contributes to expenses"), and whether guests can use all shared spaces.',
'Also define: quiet hours (typically 10PM–8AM on weeknights, midnight–9AM on weekends), and whether prior notice is required for overnight guests.']},
{h:'Common Areas and Chores',p:['Assign specific cleaning responsibilities or create a rotating schedule. Cover: kitchen (dishes must be cleaned within 24 hours, shared fridge space, who buys common supplies), bathroom (cleaning schedule, counter space allocation), living areas (vacuuming/mopping frequency), and trash (who takes it out and when).',
'Also address: can shared spaces be used for work/studying (and when), temperature settings (heating and cooling disputes are surprisingly common), and whether shoes-off is required.']},
{h:'Moving Out and Subletting',p:['How much notice must a roommate give before moving out? (60 days is standard to allow time to find a replacement.) Who is responsible for finding a replacement roommate? (Usually the leaving roommate.) Can the leaving roommate sublet their room without approval from remaining roommates? (Usually no.)',
'Security deposit: if the full deposit is in one person\'s name, how is it divided if one roommate leaves before the lease ends? Document the condition of each person\'s room at move-in (photos) so the deposit return process is fair. The landlord will return the deposit to whoever is named on the lease — internal allocation should be written.']}
],
faqList:[
{q:'Is a roommate agreement legally binding?',a:'Yes, if all roommates sign it. It is an enforceable contract between the roommates. However, a roommate agreement does not change anything in the lease — the landlord is still owed rent by whoever signed the lease, regardless of what roommates agreed between themselves. If one roommate doesn\'t pay their share, the lease-signing roommate is still liable to the landlord for the full amount.'},
{q:'What if a roommate refuses to sign a roommate agreement?',a:'A refusal to sign a basic roommate agreement is a significant red flag. If a potential roommate won\'t commit in writing to paying their share of rent, they may not be reliable. You can make signing the roommate agreement a condition of moving in — and you should.'},
{q:'Can a roommate agreement include a "house manager" role?',a:'Yes. Many roommate agreements designate one person to manage the landlord relationship (collects rent, submits maintenance requests, is the point of contact). This person is often compensated with a small rent reduction. The role and its responsibilities should be clearly defined in the agreement.'},
{q:'What happens if a roommate doesn\'t pay their share of rent?',a:'Under the roommate agreement, you can sue in small claims court for the unpaid share plus any costs you incurred covering it. The landlord cares only that full rent is paid — they will not mediate roommate disputes. Document all payment demands in writing (texts, emails) before filing.'}
],
ctaTxt:'Create a free roommate agreement',ctaHref:'/roommate-agreement-template'},

{slug:'how-to-write-a-notice-to-vacate-as-tenant',title:'How to Write a Notice to Vacate as a Tenant (2026)',
desc:'Giving your landlord proper written notice to vacate protects your security deposit and lease termination rights. Learn the format and deadlines.',
intro:'Leaving a rental without proper written notice can cost you one to two months\' rent in lease-break penalties — even if you\'re month-to-month.',
secs:[
{h:'When and How Much Notice Is Required',p:['The notice period you must give depends on: (1) your lease agreement (always check first — it may require 60 days even for month-to-month), (2) your state\'s law (default is usually 30 days for month-to-month; your state may differ), and (3) whether you are ending a fixed-term lease early (different rules apply).',
'State-specific notice rules for tenants giving notice: California — 30 days (1 year or less tenancy); California — 60 days (over 1 year); Texas — same as rent payment period (monthly = 30 days); New York — 30 days for month-to-month; Florida — 15 days for month-to-month (or one rental period). Always verify your state\'s current rule.']},
{h:'What the Notice Letter Must Say',p:['Your notice to vacate must include: (1) Your full name and the names of all tenants on the lease. (2) The rental property address. (3) The date you are giving the notice. (4) The date you intend to vacate (at least the minimum notice period from today). (5) A statement that you are terminating the tenancy. (6) Your forwarding address for the security deposit return. (7) Your signature.',
'Keep it professional and neutral — no need to explain why you\'re leaving. "I am writing to give [X] days\' notice of my intention to vacate the property at [address] on [date]" is a complete notice.']},
{h:'How to Deliver It',p:['Certified mail with return receipt is the gold standard — you get signed proof of delivery. Email is acceptable in many states (check your lease for email notice provisions) and creates a timestamp. Hand delivery with the landlord\'s signature acknowledging receipt also works.',
'Never assume verbal notice counts. "I told my landlord I was leaving" will not protect you in court. Written, documented notice is the only notice that matters.']},
{h:'Breaking a Fixed-Term Lease Early',p:['A different process applies if you are leaving before a fixed-term lease ends. You generally owe rent through the end of the lease term OR until the landlord re-rents the unit (most states require landlords to "mitigate damages" by actively looking for a new tenant). You may also owe a lease-break fee if your lease specifies one.',
'Special situations that may allow early termination without penalty: domestic violence (most states have laws allowing immediate termination for DV survivors), military deployment (SCRA allows service members to break leases with 30 days notice), landlord breach of habitability (if the unit is uninhabitable and the landlord fails to repair after notice), or constructive eviction (landlord\'s actions make the unit unlivable).']}
],
faqList:[
{q:'Can a landlord keep the security deposit if I give proper notice?',a:'Not for giving notice alone. If you give proper notice, leave the unit clean and undamaged (beyond normal wear and tear), and return all keys, the landlord must return the full deposit within the statutory deadline (14–30 days in most states). They can only deduct for legitimate damages or unpaid rent.'},
{q:'What if I need to leave immediately (domestic violence, habitability emergency)?',a:'Most states have emergency early termination rights: (1) Domestic violence — every state has laws allowing immediate or very short notice lease termination for DV victims, usually requiring a police report or restraining order. (2) Habitability — if the unit is genuinely uninhabitable (no heat, sewage issues, mold) and the landlord has failed to repair after written notice, many states allow lease termination without penalty.'},
{q:'Does my notice to vacate need to be notarized?',a:'No. A notice to vacate does not need to be notarized to be valid. It must be in writing, signed, and properly delivered. The goal is a documented paper trail — notarization adds nothing for this purpose.'},
{q:'What if the landlord claims they never received my notice?',a:'This is why delivery documentation matters. With certified mail, you have the return receipt. With email, you have the sent and read receipt. If you hand-delivered, have a witness or ask the landlord to sign a copy. "I didn\'t receive it" is almost impossible to argue against a green return receipt card.'}
],
ctaTxt:'Create a free notice to vacate letter',ctaHref:'/notice-to-vacate-template'},

{slug:'eviction-without-a-lease',title:'Evicting a Tenant Without a Written Lease: What Landlords Need to Know',
desc:'Month-to-month tenancies, verbal leases, and holdover tenants — can you evict someone with no written lease? Yes, but the rules differ.',
intro:'A written lease is not required for a landlord-tenant relationship to exist — and the eviction process still applies to tenants without one. But there are important differences.',
secs:[
{h:'Verbal Leases and Month-to-Month Tenancies',p:['A verbal lease agreement is legally binding in most states for tenancies of one year or less. If a tenant moves in, pays rent, and the landlord accepts it, a tenancy exists even without a written lease. The terms are typically inferred from the payment pattern (monthly rent payment = monthly tenancy) and local law.',
'To evict a tenant without a written lease (or with an expired lease who has become a holdover tenant), the landlord must first terminate the tenancy with proper notice, then file for eviction if the tenant doesn\'t leave. The process is the same as for a written lease — just without the written documentation.']},
{h:'Required Notice Without a Lease',p:['For month-to-month tenancies (the most common "no lease" situation), notice periods to terminate are set by state law: 30 days in most states, 60 days for tenants in California who have lived there over 1 year, 1 full rental period in Texas and Florida. Some states require the notice to terminate at the end of a rental period — not just 30 days from today.',
'If the termination is for cause (non-payment, property damage), the standard pay-or-quit or cure-or-quit notice periods apply regardless of whether there is a written lease.']},
{h:'Holdover Tenants',p:['A holdover tenant is one whose lease expired and has not signed a renewal, but continues to occupy the unit and pay rent. If the landlord accepts rent after the lease expires, most states automatically convert the tenancy to month-to-month on the same terms as the expired lease. The landlord then follows month-to-month termination rules.',
'If the landlord does not want to renew and the tenant stays past the lease expiration, the landlord can either treat the tenant as a trespasser (evict immediately in some states) or as a holdover month-to-month tenant (serve the standard termination notice). Do not accept rent after the lease expires if you want to treat the tenant as a trespasser — accepting payment creates a new tenancy.']},
{h:'Documenting the Tenancy Without a Lease',p:['When evicting without a written lease, documentation is critical: bank statements showing rent payments (establishing the tenancy and the rent amount), any text messages or emails about the tenancy, witnesses who can confirm move-in date. The court needs to establish that a landlord-tenant relationship existed, what the rent was, and when the notice was served.',
'If you\'re currently accepting cash for rent with no documentation, start issuing written receipts immediately — both to create a paper trail and because several states require landlords to provide receipts for cash rent payments.']}
],
faqList:[
{q:'Can a landlord evict a family member without a lease?',a:'Yes, but it\'s complicated. If a family member lives with you and pays rent (even informally), a landlord-tenant relationship likely exists — and you must follow the eviction process to remove them. If they never paid rent and you want them to leave, the eviction process may still apply depending on your state\'s definition of a tenancy. In some states, this is a "licensor-licensee" relationship with shorter notice periods.'},
{q:'How do you prove a tenancy existed if there\'s no written lease?',a:'Courts look at: bank records showing rent payments, checks or Venmo/CashApp receipts naming the parties and the property, text or email conversations about the tenancy, utility bills in the tenant\'s name at the address, mail in the tenant\'s name, and any witnesses. Even without a written lease, a consistent payment history is strong evidence of a tenancy.'},
{q:'Can a landlord charge more rent without a written lease?',a:'A landlord can propose a rent increase on a month-to-month tenancy (written or verbal) with proper notice — 30 days in most states, 90 days in California for increases over 10%. The tenant can accept the increase (by paying the new amount) or vacate. Without a written agreement specifying the rent, the last regularly paid amount is typically what the court recognizes.'},
{q:'Is a text message lease agreement legally binding?',a:'Potentially yes. Courts in many states have held that text message exchanges can form a binding contract if they meet the basic contract requirements: offer, acceptance, and consideration. If a landlord texts "Rent is $1,200/month starting June 1" and the tenant texts "Agreed" and pays $1,200, a court could find that a lease exists. Written leases are still far preferable.'}
],
ctaTxt:'Create a free eviction notice — all types',ctaHref:'/eviction-notice-template'},

{slug:'affidavit-of-heirship',title:'What Is an Affidavit of Heirship? How to Transfer Property Without Probate',
desc:'An affidavit of heirship lets heirs transfer real property after death without going through full probate court — in states that allow it.',
intro:'Probate can take 1–2 years and cost 3–8% of the estate\'s value. In states that allow it, an affidavit of heirship is a faster, cheaper alternative for real property transfers.',
secs:[
{h:'What an Affidavit of Heirship Does',p:['An affidavit of heirship is a sworn statement by two or more disinterested witnesses (people who are not heirs and have nothing to gain from the estate) that describes: the decedent\'s identity, date of death, marital history, children and other heirs, whether the decedent left a will, and any debts secured by the property. Once recorded in the county deed records and held for a statutory period (typically 5 years in Texas), it can be used to establish that heirs have clear title.',
'It does not require a court proceeding — just two witnesses, a notary, and the county recorder\'s filing fee.']},
{h:'Which States Allow It',p:['Affidavit of heirship procedures are most well-established in: <strong>Texas</strong> (5-year holding period, then usable to convey title), <strong>Colorado</strong>, <strong>Kansas</strong>, <strong>Nebraska</strong>, <strong>Oklahoma</strong>, and several other states. California allows a "Petition to Determine Succession to Real Property" for smaller estates. Some states use similar instruments under different names.',
'California, New York, Florida, and other states with robust probate alternatives (small estate affidavits, summary administration, transfer-on-death deeds) may not recognize affidavits of heirship for real property. Check your state\'s probate code or consult a local estate attorney.']},
{h:'Requirements for a Valid Affidavit of Heirship',p:['In Texas (the most widely used version): (1) Signed by two disinterested witnesses who personally knew the decedent. (2) Witnesses must state they are not heirs and have no interest in the estate. (3) Notarized. (4) Recorded in the county real property records where the property is located. (5) Held of record for 5 years before it establishes clear title.',
'The affidavit must accurately describe the property (legal description from the deed, not just the address), the decedent\'s full identity and date of death, and all heirs — even those who may not be taking the property.']},
{h:'Limitations and Risks',p:['An affidavit of heirship does not: clear title to property encumbered by a mortgage (the lender may still have rights), address community property claims from a surviving spouse, resolve disputes among competing heirs, or override a valid will (if the decedent left a will, probate is required). Title insurance companies may be reluctant to insure property transferred by affidavit of heirship without the 5-year holding period having elapsed.',
'For estates with significant assets, multiple properties, debts, or family disputes, a formal probate proceeding provides stronger legal protection for all parties. The affidavit of heirship is best suited for simple situations: one property, no mortgage, no disputes among heirs.']}
],
faqList:[
{q:'Can an heir sign their own affidavit of heirship?',a:'No. The witnesses must be "disinterested" — they cannot be heirs, legatees, or anyone who would benefit from the estate. Typically, long-time family friends, neighbors, clergy, or coworkers who knew the decedent well serve as witnesses. If an heir signs, the affidavit is invalid.'},
{q:'What if there is a will?',a:'If the decedent left a will, the estate generally must go through probate (or a simplified probate process for small estates). An affidavit of heirship is typically used when there is no will, not when there is one. Using an affidavit to bypass a valid will could be challenged by other heirs or legatees.'},
{q:'Does an affidavit of heirship transfer title immediately?',a:'In most states, recording the affidavit gives heirs color of title but the chain of title is not considered fully established until the holding period expires (5 years in Texas). During that period, the affidavit can be challenged. After the holding period, the title becomes much more difficult to challenge and title insurance companies will generally insure it.'},
{q:'Can I use an affidavit of heirship to sell the property?',a:'After the holding period (5 years in Texas), generally yes — you can convey the property using a deed that references the recorded affidavit as the basis for title. Before the holding period, some buyers and title companies may require additional documentation or a quiet title lawsuit to insure the transaction.'}
],
ctaTxt:'Create a free affidavit with notary block',ctaHref:'/affidavit-template'},

{slug:'independent-contractor-agreement-what-to-include',title:'Independent Contractor Agreement: 8 Clauses You Must Have',
desc:'A well-drafted IC agreement prevents worker misclassification claims and protects both parties. Here are the 8 non-negotiable clauses.',
intro:'An independent contractor agreement does two jobs: it documents the working relationship (protecting against misclassification claims) and defines the project terms (preventing scope disputes).',
secs:[
{h:'1. Contractor Status and Control Clause',p:['This is the most legally important clause. It must state that: (1) The contractor is an independent contractor, not an employee. (2) The contractor controls the means and methods of their work, not the company. (3) The contractor provides their own tools and equipment (or specify if company provides tools, and why). (4) The contractor may work for other clients.',
'Courts look past labels to the actual working relationship. The clause alone doesn\'t create contractor status — but it documents the intent, and when paired with a working relationship that actually reflects contractor independence, it is strong evidence.']},
{h:'2. Scope of Work and Deliverables',p:['Define exactly what the contractor will produce or perform: specific deliverables, acceptance criteria, revision rounds, and delivery timeline. Vague scope is the source of almost every contractor dispute.',
'"Develop a mobile app" is a trap. "Develop an iOS app as specified in Exhibit A (attached) including features X, Y, Z, delivered as working source code by March 31, 2026, with up to 3 rounds of revision based on client feedback" is a contract.']},
{h:'3. Payment, Invoicing, and Late Payment',p:['Specify: rate (hourly or fixed), total amount (if fixed), payment schedule (milestone-based, monthly, or on delivery), invoicing terms (contractor invoices within X days of milestone, client pays within Y days of receipt), and a late payment penalty (typically 1.5%/month).',
'For fixed-price contracts: define a change order process. If the client requests work outside the defined scope, the contractor submits a change order with an additional price, and work proceeds only after written approval. Without this, scope creep is unpaid labor.']},
{h:'4–8. IP Assignment, Confidentiality, Termination, Governing Law, No-Hire',p:['<strong>IP Assignment</strong>: "Upon receipt of full payment, Contractor assigns all intellectual property rights in the Work Product to Company." Add a provision that the contractor retains rights to pre-existing work (tools, libraries, prior code) they bring to the project. <strong>Confidentiality</strong>: define what is confidential and how long the obligation lasts (2–5 years is standard). <strong>Termination</strong>: either party may terminate with 14 days\' notice; client pays for work completed to date. <strong>Governing law</strong>: name the state. <strong>No-hire/non-solicitation</strong>: company won\'t hire contractor\'s employees; contractor won\'t solicit company\'s clients (for 12–18 months after engagement ends — this is generally more enforceable than a non-compete).']}
],
faqList:[
{q:'Does an IC agreement prevent worker misclassification claims?',a:'It helps significantly but does not guarantee protection. Courts and government agencies look at the actual working relationship, not just the contract label. The agreement documents intent. If the working relationship also reflects contractor independence (contractor sets own hours, uses own tools, works for multiple clients, controls how work is done), the combination is strong evidence of contractor status.'},
{q:'Should the IC agreement or a SOW define the scope?',a:'For ongoing contractor relationships, a master IC agreement covers the general terms (status, IP, confidentiality, payment terms, termination) and individual Statements of Work (SOWs) define each specific project. This is cleaner than updating one long agreement for every new project.'},
{q:'Can the same contractor agreement be used with all contractors?',a:'For similar types of work, yes. But adjust the scope of work, payment terms, and IP provisions for each engagement. An IC agreement for a software developer needs different IP terms than one for a photographer or marketing consultant — the default copyright rules differ for these types of work.'},
{q:'What if the contractor refuses to sign an IP assignment?',a:'Some contractors (especially photographers, illustrators, writers) routinely negotiate to retain copyright and grant only a license. This is legitimate. If the contractor retains copyright, make sure the license terms are extremely clear: what can you use the work for, in what channels, for how long, and can you modify it? An exclusive perpetual license is close to assignment in practical effect.'}
],
ctaTxt:'Create a free independent contractor agreement',ctaHref:'/independent-contractor-agreement-template'},

{slug:'how-to-transfer-a-car-title',title:'How to Transfer a Car Title After a Private Sale',
desc:'Step-by-step guide to transferring a vehicle title after a private sale — both buyer and seller steps, state deadlines, and common mistakes.',
intro:'The title is what makes you the legal owner. A bill of sale proves you bought the car; the title transfer makes it official in state records.',
secs:[
{h:'Seller\'s Steps Before the Sale',p:['Before handing over the keys: (1) Locate the title. If it\'s lost, apply for a duplicate through your state DMV before selling — it can take 1–4 weeks. (2) Satisfy any liens. If there is a lienholder (bank, credit union) on the title, they must release the lien before you can transfer clear title. Contact the lienholder and pay off the loan or get a lien release. (3) Complete the seller\'s section on the back of the title: odometer reading, sale price, date, buyer\'s name and address, and your signature. Some states require notarization.',
'Write all information exactly as required by your state — errors on the title require a correction process at the DMV.']},
{h:'The Bill of Sale',p:['A bill of sale is separate from the title but equally important. It records: VIN, year/make/model, sale price, date, and both parties\' signatures. Some states require a bill of sale for title transfer; others just need the title. Even where not required, the bill of sale protects both parties: the buyer has proof of purchase price (for tax purposes), and the seller has documentation of the transaction.',
'Retain a signed copy. The IRS and state DMV may ask about the sale price.']},
{h:'Buyer\'s Steps After the Sale',p:['After taking possession of the signed title and bill of sale: (1) Take both documents to your county DMV or motor vehicle office within the deadline (typically 30 days). (2) Bring government-issued photo ID. (3) Pay the title transfer fee ($15–$85 depending on state) and sales tax on the purchase price. (4) If the vehicle has an odometer over 10 years old, the odometer disclosure requirement may not apply (varies by state).',
'In most states, you must have proof of insurance before driving the vehicle off the lot or registering it. Do not drive an unregistered, uninsured vehicle to the DMV.']},
{h:'Seller\'s Steps After the Sale',p:['(1) Remove license plates — in most states, plates belong to the seller, not the vehicle. Transfer them to your new vehicle or turn them in. (2) File a "Notice of Transfer" or "Release of Liability" with your state DMV (online in most states — free). This officially removes you from responsibility for the vehicle. Without this notice, you can receive red-light camera tickets, toll violations, and liability claims from the new owner\'s accidents until the buyer completes the title transfer. (3) Cancel or transfer your auto insurance policy.']}
],
faqList:[
{q:'What if the title is in both names with "or" vs "and"?',a:'"Owner A or Owner B" — either person can sign the title transfer alone. "Owner A and Owner B" — both must sign. This is why "and" joint ownership creates complications when one owner is unavailable (divorce, death, estrangement). Check the exact language on your title before the sale.'},
{q:'What if the buyer never registers the car?',a:'This is why the seller\'s "Notice of Transfer" is critical. If you file it promptly, you are released from liability for anything the vehicle does after the sale. If you don\'t file it and the buyer never registers the car, you can receive violations, property tax bills, and even be implicated in accidents associated with the vehicle.'},
{q:'Can I sell a car without a title?',a:'Technically yes in some states for very old vehicles, but it is strongly discouraged. Without a title, the buyer cannot register the vehicle or prove legal ownership. The car may have an undisclosed lien, may be stolen, or may be a salvage vehicle. Never buy a car without a clean title.'},
{q:'What is a "title jumping" violation?',a:'"Title jumping" occurs when a buyer resells a vehicle without transferring the title into their name first — the title skips a link in the chain. This is illegal in all states and can result in fines and difficulty establishing clean title. Dealers are specifically prohibited from title jumping.'}
],
ctaTxt:'Create a free bill of sale for any vehicle',ctaHref:'/bill-of-sale-template'},

{slug:'how-to-enforce-a-non-compete',title:'How to Enforce a Non-Compete Agreement (Employer\'s Guide)',
desc:'An employer\'s guide to enforcing non-compete agreements — from cease and desist to TRO to injunction — and when courts grant them.',
intro:'When a former employee joins a competitor in violation of a non-compete, you have a narrow window to act. Courts grant injunctions quickly — but only if you move fast and have the right facts.',
secs:[
{h:'Step 1: Assess Enforceability First',p:['Before spending money on litigation, evaluate whether your non-compete is likely enforceable in your state. If the employee is in California, Minnesota, North Dakota, or Oklahoma, stop — courts there will not enforce employee non-competes regardless of what the contract says (and in California, trying to enforce one can expose you to statutory penalties under AB 2288).',
'In states that enforce non-competes, the threshold questions: Is the duration reasonable (generally 1–2 years max)? Is the geographic scope appropriate for the actual business territory? Is the activity restriction limited to truly competitive work, not just "anything in the industry"? Did the employee receive adequate consideration when they signed? If the answers are yes, you have a viable case.']},
{h:'Step 2: Send a Cease and Desist Letter',p:['Before filing suit, send a detailed cease and desist letter to both the former employee and the new employer. The letter to the new employer is important — it puts them on legal notice of the non-compete, which can make them liable for tortious interference if they continue employing the person knowing they are in breach.',
'Some new employers, upon receiving a cease and desist, immediately reassign the employee or require them to resolve the dispute before continuing employment. This is the fastest resolution and costs the least. Give a 10–14 day response deadline.']},
{h:'Step 3: File for a Temporary Restraining Order (TRO)',p:['If the C&D is ignored and the competitive activity continues, file for a TRO in state court. A TRO can be obtained within 24–72 hours of filing, ex parte (without the defendant present), if you can show: (1) likelihood of success on the merits, (2) irreparable harm (harm that money damages can\'t fix — like loss of trade secrets or client relationships), (3) balance of hardships favors the employer, and (4) the injunction serves the public interest.',
'"Irreparable harm" is the hardest element. Courts are skeptical that losing one employee to a competitor is "irreparable." You need evidence of specific harm — trade secret disclosure, solicitation of specific named clients, using confidential information.']},
{h:'What Courts Award and What They Don\'t',p:['If you win the TRO and then the preliminary injunction hearing (usually 10–14 days later), the court orders the employee to stop the competitive activity for the restriction period. They may also order them to resign from the new employer.',
'Damages for non-compete violations are notoriously hard to prove — courts require concrete financial harm traceable to the breach. Most non-compete cases seek injunctive relief only, not damages. If trade secrets were misappropriated, the federal Defend Trade Secrets Act (DTSA) provides a separate cause of action with potentially stronger remedies.']}
],
faqList:[
{q:'Does a non-compete survive termination for any reason?',a:'Yes, in most cases. Non-competes typically state they survive termination "for any reason." However, some courts are more skeptical of enforcing a non-compete against an employee who was laid off (not fired for cause, not quit) — especially if the non-compete provides no compensation during the restriction period. Massachusetts, for example, requires paying at least 50% of base salary during the restriction period.'},
{q:'Can you sue the new employer for hiring someone covered by a non-compete?',a:'Yes — this is called tortious interference with contract. Once you send the new employer a C&D letter, they have actual notice of the non-compete. Continuing to employ the person after notice can make them jointly liable. The lawsuit would allege tortious interference with your contractual relationship with the former employee.'},
{q:'How quickly does a TRO proceeding move?',a:'Very quickly by litigation standards. A TRO application can be filed and heard within 1–3 days of filing. A preliminary injunction hearing follows in 10–14 days. This is why acting immediately (within days of learning of the breach) is critical — courts are less likely to grant a TRO if you waited weeks before acting.'},
{q:'What if the non-compete was never signed?',a:'If no signed non-compete agreement exists, you generally cannot enforce one. Verbal non-compete agreements are generally unenforceable (they fall under the statute of frauds in most states). The exception: if trade secrets were misappropriated, you can still pursue a DTSA claim even without a non-compete agreement.'}
],
ctaTxt:'Create a state-specific non-compete agreement',ctaHref:'/non-compete-agreement-template'},

{slug:'single-member-vs-multi-member-llc',title:'Single-Member vs Multi-Member LLC: Key Differences',
desc:'Single-member and multi-member LLCs are taxed differently and have different legal exposure. Learn the key differences before you form.',
intro:'Choosing between a single-member and multi-member LLC is one of the first structure decisions you make — and it affects taxes, legal protection, and how the IRS views your business.',
secs:[
{h:'Tax Treatment: The Critical Difference',p:['A <strong>single-member LLC (SMLLC)</strong> is treated as a "disregarded entity" for federal tax purposes — the IRS treats it as a sole proprietorship. You report income and expenses on Schedule C of your personal return and pay self-employment tax (15.3%) on net profit. No separate business tax return is required.',
'A <strong>multi-member LLC</strong> is taxed as a partnership by default. It must file a Form 1065 (partnership return), and each member receives a K-1 showing their share of income and losses, which flows to their personal returns. Self-employment tax treatment varies based on whether members are active in the business.']},
{h:'Legal Protection Differences',p:['The LLC\'s liability shield applies to both types — members of either are generally not personally liable for LLC debts. However, courts have historically been slightly more willing to pierce the corporate veil on single-member LLCs than on multi-member LLCs, because a sole owner has more opportunity to treat the LLC as their personal alter ego.',
'Both types need: a separate business bank account, separate books, operating agreement, and consistent use of the LLC name in contracts. For a SMLLC, maintaining this separation is even more critical because there is no partner to act as a check.']},
{h:'Management and Operating Agreement',p:['A SMLLC operating agreement is simpler — it mainly documents that the LLC is legitimate, defines the member\'s authority, and establishes what happens to the LLC if the member dies or becomes incapacitated. Many states don\'t require SMLLC operating agreements, but having one is still essential for liability protection and estate planning.',
'A multi-member LLC operating agreement is much more detailed — it must address: how decisions are made, how profits and losses are allocated (not always equal), what happens when a member wants to leave, how new members are admitted, deadlock resolution, and buy-out provisions. A multi-member LLC without a detailed operating agreement is a lawsuit waiting to happen.']},
{h:'Converting Between Types',p:['A SMLLC becomes a multi-member LLC the moment a new member is admitted. This triggers a change in federal tax status (from disregarded entity to partnership). File a new Form SS-4 with the IRS for a new EIN, update the operating agreement, and notify your bank. Conversely, if a multi-member LLC loses all but one member (buyout, departure), it reverts to SMLLC tax treatment.',
'Both conversions are mechanically simple but have tax implications — especially if the LLC holds appreciated assets. Consult a CPA before admitting or buying out a member to understand the tax consequences.']}
],
faqList:[
{q:'Does a single-member LLC get the same liability protection as a multi-member LLC?',a:'Technically yes — the liability shield is the same. In practice, courts scrutinize single-member LLCs more carefully for veil-piercing (treating the LLC as the owner\'s alter ego). Maintaining strict separation between personal and business finances is especially important for SMLLCs.'},
{q:'Can a married couple form a single-member LLC?',a:'In community property states, a married couple can treat a two-member LLC as a single-member LLC (a "qualified joint venture") and avoid filing a partnership return. Both spouses report their share on Schedule C. This is a significant simplification for couples running a business together in community property states.'},
{q:'What is the self-employment tax difference between SMLLC and multi-member?',a:'For SMLLCs, all net profit is subject to self-employment tax. For multi-member LLCs, the SE tax treatment of each member depends on their role — active members who provide services pay SE tax on their share; passive investors generally don\'t. Both types can elect S-Corp status to reduce SE tax on distributions.'},
{q:'Can a single-member LLC have employees?',a:'Yes. A SMLLC can employ people — employees are not members. The LLC gets an EIN, handles payroll, pays employer taxes, and the employee has nothing to do with the LLC\'s ownership structure. The distinction is between members (owners) and employees (workers).'}
],
ctaTxt:'Create your free LLC operating agreement',ctaHref:'/llc-operating-agreement-template'},

];

posts.forEach(function(p){
  fs.writeFileSync(B+p.slug+'.html', art(p.slug,p.title,p.desc,p.intro,p.secs,p.faqList,p.ctaTxt,p.ctaHref));
});
console.log('Blog batch 4: '+posts.length+' articles');
